<html>
<head>
<title>РЭУ</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<META name="Author" content:"http://ailus.ru"><meta name="Copyright" content="http://ailus.ru">
</head>
<body leftmargin="0" topmargin ="0" marginwidth ="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">
<table border=1 width=100% height=20%>
<td width=100% height=20% align=center> Лабороторные работы <br> студентов группы ПИ-153 Кириллова Н.О., Циркель Т.А. <br> Проверил Назимов А.С.</td>
</table>
<table border=1 width=100% height=70%>
<td width=30% height=70% align=left> 
<a href="orderform.php"> Первая лаб </a>
<br><br>
<a href="orderform_2.php"> Вторая лаб </a>
<br><br>
<a href="orderform_3.php"> Третья лаб </a>
<br><br>
<a href="orderform_3.1.php"> 3.1 </a>
<br><br>
<a href="orderform_4.php"> Четвертая лаб </a>
<br><br>
<a href="orderform_5.php"> Пятая лаб </a>
</td>


<td width=70% height=70% align=center> 
